### ISSUE TITLE
calculus.org: calc-radians-mode suggestion and Taylor series correction

### ISSUE THREAD

**Issue by tmdemelo** [ahyatt/emacs-calc-tutorials#1]
In the calculus tutorial, you might like to use angles in radians with `m r` (`calc-radians-mode`). This way, integrals and derivatives of trigonometric functions are further simplified. It seems the tutorial starts in `calc-degrees-mode`, which might explain the issue you observed with the derivative, but I couldn't reproduce it.

Also, regarding the Taylor expansion, to get the result shown in the tutorial, you must ask for 9 terms instead of 6.  The [calc manual](https://www.gnu.org/software/emacs/manual/html_node/calc/Taylor-Series.html) says:

> Note that many series expansions have coefficients of zero for some terms, so you may appear to get fewer terms than you asked for.

When `calc` asks for _number of terms_, it might be useful to think about _polynomial degree_ instead, which is more close to what we actually get in the end. 

Thanks a lot for the tutorials.

**Comment by ahyatt** [comment]
Thanks for the feedback!  All that makes a lot of sense.  I'll look at the tutorial again soon and update.

**Comment by ahyatt** [comment]
Thanks again for the tips.  I couldn't reproduce my earlier results either.  I fixed things up using your helpful suggestion of using radians in commit dea22db6498d92e5801e5fdbe93ef7f1dd948367.
